[package]
name = "parser"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] } 
serde-aux = "0.1"

[dev-dependencies]
tempfile = "3.10"
