[configuration]
buggify = true
minimumReplication = 3

[[test]]
testTitle = 'NemesisTest'

    [[test.workload]]
    testName = 'ReadWrite'
    testDuration = 30.0
    transactionsPerSecond = 1000.0

    [[test.workload]]
    # Introduce network partitions
    testName = 'RandomClogging'
    testDuration = 30.0
    # Unclog them in reversed order
    swizzle = 1
    
    [[test.workload]]
    # Reboot processes
    testName = 'Attrition'
    testDuration = 30.0
    
    [[test.workload]]
    # Introduce specific network partitions errors between proxies and tLogs
    testName = 'Rollback'
    testDuration = 30
    
    [[test.workload]]
    # Change configuration of the database
    testName = 'ChangeConfig'
    # Move consensus-based processes around
    coordinators = 'auto'
